ALTER TABLE libraries ADD COLUMN enabled INTEGER NOT NULL DEFAULT 1;
ALTER TABLE libraries ADD COLUMN revision INTEGER NOT NULL DEFAULT 0;
ALTER TABLE profiles ADD COLUMN revision INTEGER NOT NULL DEFAULT 0;
ALTER TABLE jobs ADD COLUMN full_scan INTEGER NOT NULL DEFAULT 0;
ALTER TABLE jobs ADD COLUMN reused_files INTEGER NOT NULL DEFAULT 0;
ALTER TABLE jobs ADD COLUMN inspected_files INTEGER NOT NULL DEFAULT 0;
ALTER TABLE processing_jobs ADD COLUMN cache_cleaned INTEGER NOT NULL DEFAULT 0;
CREATE TABLE maintenance_state (name TEXT PRIMARY KEY, last_success INTEGER, last_attempt INTEGER, error TEXT);
