"""Generate or check target-specific Rust dependency notices from locked Cargo sources."""
import argparse
import hashlib
import json
from pathlib import Path
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[1]
NOTICE_PREFIXES = ('LICENSE', 'LICENCE', 'COPYING', 'NOTICE', 'COPYRIGHT', 'AUTHORS')


def checkout_root(package):
    """The root of the Cargo git checkout holding a git-sourced package, if any."""
    if not (package.get('source') or '').startswith('git+'):
        return None
    for directory in Path(package['manifest_path']).parent.resolve().parents:
        if (directory / '.cargo-ok').is_file():
            return directory
    return None


def notice_files(package):
    root = Path(package['manifest_path']).parent.resolve()
    selected = {
        path for path in root.rglob('*')
        if path.is_file() and any(
            part.upper().startswith(NOTICE_PREFIXES)
            for part in path.relative_to(root).parts
        )
    }
    if package.get('license_file'):
        selected.add(root / package['license_file'])
    base, prefix = root, ''
    repository = checkout_root(package)
    if not selected and repository is not None:
        # A crate in a git workspace may rely on the repository's top-level license.
        selected = {
            path for path in repository.iterdir()
            if path.is_file() and path.name.upper().startswith(NOTICE_PREFIXES)
        }
        base, prefix = repository, 'repository/'
    if not selected:
        raise ValueError(f"No license/notice files found: {package['name']} {package['version']}")
    notices = []
    for path in sorted(selected):
        if not path.resolve().is_relative_to(base):
            raise ValueError(f'License file escapes package: {path}')
        content = path.read_text(encoding='utf-8')
        if not content.strip():
            raise ValueError(f'Empty license/notice file: {path}')
        notices.append((prefix + path.relative_to(base).as_posix(), content))
    return notices


def render(metadata, target, lock_bytes):
    workspace = set(metadata['workspace_members'])
    # Cargo metadata includes build and development dependencies as well as runtime
    # dependencies. Retain their notices conservatively, without claiming each is linked.
    packages = sorted(
        (p for p in metadata['packages'] if p['id'] not in workspace),
        key=lambda p: (p['name'], p['version'], p.get('source') or ''),
    )
    texts = {}
    entries = []
    for package in packages:
        if not package.get('license') and not package.get('license_file'):
            raise ValueError(f"Missing license declaration: {package['name']}")
        entry = [f"{package['name']} {package['version']}",
                 f"License: {package.get('license') or 'see license file'}",
                 f"Source: {package.get('source') or 'local dependency'}"]
        if package.get('repository'):
            entry.append(f"Repository: {package['repository']}")
        for name, content in notice_files(package):
            digest = hashlib.sha256(content.encode()).hexdigest()
            texts[digest] = content
            entry.append(f'  {name} -> text {digest}')
        entries.append('\n'.join(entry))
    header = f'''THIRD-PARTY RUST DEPENDENCY NOTICES
Generated by scripts/third_party_notices.py; do not edit manually.
Target: {target}
Cargo.lock SHA-256: {hashlib.sha256(lock_bytes).hexdigest()}
Dependency packages: {len(packages)}

Includes resolved runtime, build, and development dependencies for this target
and Cargo's default feature selection. Identical texts are included once and
referenced by SHA-256. License expressions are preserved, not relicensed.
Demuxe, FFmpeg, and optional providers are outside this Rust inventory.
Distributions containing them preserve their own supplied license materials.
See THIRD_PARTY.md for scope and distribution requirements.

'''
    sections = [header, '\n\n'.join(entries), '\n\nLICENSE AND NOTICE TEXTS\n']
    for digest, content in sorted(texts.items()):
        sections.append(f'\n===== text {digest} =====\n{content}\n')
    return ''.join(sections)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--target', default='aarch64-apple-darwin')
    parser.add_argument('--output', type=Path, default=ROOT / 'THIRD_PARTY_NOTICES.txt')
    parser.add_argument('--check', action='store_true', help='Fail if output is missing or stale')
    parser.add_argument('--offline', action='store_true', help='Require cached Cargo packages')
    args = parser.parse_args()
    command = ['cargo', 'metadata', '--locked', '--format-version', '1',
               '--filter-platform', args.target]
    if args.offline:
        command.append('--offline')
    try:
        lock_bytes = (ROOT / 'Cargo.lock').read_bytes()
        metadata = json.loads(subprocess.check_output(command, cwd=ROOT))
        output = render(metadata, args.target, lock_bytes)
        if (ROOT / 'Cargo.lock').read_bytes() != lock_bytes:
            raise ValueError('Cargo.lock changed during notice generation; retry')
        if args.check:
            if not args.output.exists() or args.output.read_text(encoding='utf-8') != output:
                raise ValueError('Third-party notices are missing or stale; regenerate with the same target/output')
            print(f'Notices are current for {args.target}: {args.output.name}')
        else:
            args.output.parent.mkdir(parents=True, exist_ok=True)
            args.output.write_text(output, encoding='utf-8')
            print(f'Generated notices for {args.target}: {args.output}')
    except (OSError, ValueError, subprocess.CalledProcessError) as error:
        print(f'Notice generation failed: {error}', file=sys.stderr)
        return 1
    return 0


if __name__ == '__main__':
    sys.exit(main())
